# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed character', max_length=64)),
                ('avatar', models.CharField(default='', max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendShip', models.IntegerField(default=50)),
                ('char', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='norns.Character')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='nextDialogue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='norns.Dialogue'),
        ),
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='characterrel',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characterRels', to='norns.Player'),
        ),
    ]
