# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norns', '0002_auto_20171031_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='player',
        ),
        migrations.RenameField(
            model_name='characterrel',
            old_name='friendShip',
            new_name='friendship',
        ),
        migrations.AddField(
            model_name='dialogue',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='norns.Character'),
        ),
        migrations.AddField(
            model_name='player',
            name='charisma',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='fortune',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='health',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='intel',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='player',
            name='luck',
            field=models.IntegerField(default=50),
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
