# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norns', '0004_auto_20171105_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='name',
            field=models.CharField(default='unnamed option', max_length=64),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='name',
            field=models.CharField(default='unnamed dialogue', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='nextDialogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='norns.Dialogue'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='player unknown', max_length=32, unique=True),
        ),
    ]
