# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norns', '0005_auto_20171105_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='unnamed', max_length=64),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='name',
            field=models.CharField(default='unnamed', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(default='unnamed', max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='unnamed', max_length=32, unique=True),
        ),
    ]
