# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norns', '0006_auto_20171105_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='nickname',
            new_name='name',
        ),
    ]
