# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norns', '0008_auto_20171105_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProxyUser',
        ),
        migrations.AlterField(
            model_name='player',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
    ]
