# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norns', '0009_auto_20171105_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.CharField(default='a character description', max_length=1024),
        ),
        migrations.AlterField(
            model_name='character',
            name='avatar',
            field=models.ImageField(upload_to='norns.media'),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(upload_to='norns.media'),
        ),
    ]
