# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norns', '0010_auto_20171105_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='nextDialogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentOptions', to='norns.Dialogue'),
        ),
    ]
