# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import norns.models


class Migration(migrations.Migration):

    dependencies = [
        ('norns', '0011_auto_20171109_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField(default=0)),
                ('luck', models.IntegerField(default=50)),
                ('intel', models.IntegerField(default=50)),
                ('fortune', models.IntegerField(default=50)),
                ('charisma', models.IntegerField(default=50)),
                ('health', models.IntegerField(default=50)),
            ],
            bases=(norns.models.DisplayNameMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='player',
            name='charisma',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fortune',
        ),
        migrations.RemoveField(
            model_name='player',
            name='health',
        ),
        migrations.RemoveField(
            model_name='player',
            name='intel',
        ),
        migrations.RemoveField(
            model_name='player',
            name='luck',
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gameState', to='norns.Player'),
        ),
    ]
