# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('norns', '0012_auto_20171117_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gameStates', to='norns.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(default='norns.media/default-avatar.png', upload_to='norns.media'),
        ),
    ]
