# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import norns.models


class Migration(migrations.Migration):

    dependencies = [
        ('norns', '0013_auto_20171120_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsModifer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed', max_length=64)),
                ('modifiers', jsonfield.fields.JSONField(default={})),
            ],
            bases=(norns.models.DisplayNameMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='charisma',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='fortune',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='health',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='intel',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='luck',
        ),
        migrations.RemoveField(
            model_name='option',
            name='customScripts',
        ),
        migrations.AddField(
            model_name='gamestate',
            name='JSONField',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='option',
            name='statsModifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='norns.StatsModifer'),
        ),
    ]
