# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 16:38
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('norns', '0014_auto_20171129_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='JSONField',
            field=jsonfield.fields.JSONField(default={'charisma': 10, 'fortune': 10, 'health': 10, 'intelligence': 10, 'luck': 10, 'social': 10}),
        ),
        migrations.AlterField(
            model_name='statsmodifer',
            name='modifiers',
            field=jsonfield.fields.JSONField(default={'charisma': 10, 'fortune': 10, 'health': 10, 'intelligence': 10, 'luck': 10, 'social': 10}),
        ),
    ]
