# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 16:43
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('norns', '0016_auto_20171129_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='JSONField',
            field=jsonfield.fields.JSONField(default='{"intelligence": 10, "health": 10, "luck": 10, "yanzhi": 10, "charisma": 10, "social": 10, "fortune": 10}'),
        ),
        migrations.AlterField(
            model_name='statsmodifer',
            name='modifiers',
            field=jsonfield.fields.JSONField(default='{"intelligence": 10, "health": 10, "luck": 10, "yanzhi": 10, "charisma": 10, "social": 10, "fortune": 10}'),
        ),
    ]
