# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20170825_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='alias',
            field=models.CharField(default='Default Account', max_length=32),
        ),
        migrations.AlterField(
            model_name='position',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='position',
            name='payoff',
            field=models.FloatField(default=0.0),
        ),
    ]
