# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 10:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20170826_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='is_cleared',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='isFinished',
        ),
        migrations.AddField(
            model_name='option',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (5, 'RESOLVED'), (10, 'REJECTED')], default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='clear_timestamp',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='position',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING_PREDICTION'), (5, 'PENDING_CLEARING'), (10, 'CLEARED'), (100, 'CLEAR_FAILED')], default=0),
        ),
        migrations.AddField(
            model_name='prediction',
            name='status',
            field=models.IntegerField(choices=[(0, 'DRAFT'), (5, 'STAGED'), (10, 'OPEN'), (15, 'CLOSED'), (20, 'SETTLED')], default=0),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='startAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Open at'),
        ),
    ]
